Repository OCEAN-xyz/datum_gateway, pull requests merged in 2025-01, with the labels that each got.

#45 Add a datum_conf.c check for no pool, but mining only
  src/datum_conf.c
Labels: bug

#58 EmbedResources: Use character literals for generated header
  cmake/script/EmbedResources.cmake
Labels: portability

#25 Support web interface commands without Javascript
  src/datum_api.c
  src/datum_utils.c
  src/datum_utils.h
Labels: enhancement

#59 Bugfix: Max possible template transactions inconsistent across functions
  src/datum_blocktemplates.c
  src/datum_stratum.c
Labels: bug
