Repository OCEAN-xyz/datum_gateway, pull requests merged in 2025-03, with the labels that each got.

#68 Bugfix: Socket state can change between epoll and send
  src/datum_gateway.c
Labels: bug

#62 Bugfix: api: Free parsed JSON for cmd POST
  src/datum_api.c
Labels: bug

#18 Format output of -? better
  src/datum_conf.c
Labels: documentation

#64 Allow API access before initialisation completes, and wait indefinitely for bitcoind to provide a template
  src/datum_api.c
  src/datum_blocktemplates.c
  src/datum_blocktemplates.h
  src/datum_stratum.c
Labels: enhancement

#71 Add datum process uptime
  src/datum_api.c
  src/datum_utils.c
  src/datum_utils.h
  www/home.html
Labels: enhancement

#75 Fix minor bugs in socket edgecases
  src/datum_api.c
  src/datum_sockets.c
Labels: bug

#49 Support for editing config file (to an extent) via web dashboard
  CMakeLists.txt
  src/datum_api.c
  src/datum_api.h
  src/datum_blocktemplates.c
  src/datum_conf.c
  src/datum_conf.h
  src/datum_gateway.c
  src/datum_gateway.h
  src/datum_jsonrpc.c
  src/datum_jsonrpc.h
  src/datum_utils.c
  src/datum_utils.h
  www/clients_top.html
  www/coinbaser_top.html
  www/config.html
  www/config_errors.html
  www/config_restart.html
  www/home.html
  www/threads_top.html
Labels: enhancement

#82 build/EmbedResources: Omit unnecessary/extra explicit null byte
  cmake/script/EmbedResources.cmake
Labels: bug

#87 Include example config, verify it is up-to-date, and install it
  .gitignore
  CMakeLists.txt
  cmake/script/VerifyExample.cmake
  doc/example_datum_gateway_config.json
  src/datum_conf.c
  src/datum_conf.h
  src/datum_gateway.c
  src/datum_gateway.h
Labels: documentation

#89 Install README (and its diagram) to doc dir (incl. bugfix)
  CMakeLists.txt
  debian/rules
Labels: bug, documentation

#91 api: Workaround Safari negligence by falling back to MD5 digest for it alone
  src/datum_api.c
Labels: portability

#93 Bugfix: sockets: Ensure listen_socks[1] is always initialized
  src/datum_sockets.c
Labels: bug
